language: python

# Use the new container-based Travis infrastructure.
sudo: false

# Cache pip packages. Explicitly name the pip-cache directory since we
# use a custom `install` step which annuls `cache: pip`.
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pip-accel

# Try OS X.
os:
  - linux
  #- osx

env:
#  - PYCRYPTO_VERSION=2.4.1
#  - PYCRYPTO_VERSION=2.6.1

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"

matrix:
  allow_failures:
      # Just tests how PyInstaller performs with upcoming Python 3.6
      - python: "nightly"
      # Ignore failures from OS X.
      - os: osx

addons:
  # Ubuntu 12.04 (LTS) packages installed into this Travis-CI container. Since
  # Ubuntu 12.04 provides *NO* Python 3 packages prefixed by "python3-", only
  # Python 2.7 packages prefixed by "python-" are installable. Installing only
  # Python 2.7 packages would be useless, however! Python packages should thus
  # be installed by "pip" via the "test/requirements-library.txt" specification.
  #
  # Travis-CI intends to add support for Ubuntu 14.04 (LTS) at some future date.
  # To track progress on this long-standing issue, see:
  #
  #     https://github.com/travis-ci/travis-ci/issues/2046
  apt:
    packages:
    # lxml dependencies.
    - libxml2-dev
    - libxslt1-dev
    # pyttsx dependencies.
    - libespeak1
    # SciPy dependencies.
    - gfortran
    - libatlas-base-dev

before_install:
  # Compile bootloader
  - cd bootloader
  - python waf distclean all --no-lsb
  - cd ..


install:
  # Update pip.
  - python -m pip install -U pip
  # Install PyInstaller.
  - pip install -e .

  # Install dependencies for tests.
  - pip install -U -r tests/requirements-tools.txt
  - pip install -U -r tests/requirements-linux.txt

script:
  # Run tests and speed them up by sending them to multiple CPUs.
  # Run unitttest first.
  - py.test -n 3 --maxfail 3 tests/unit/ tests/

notifications:
    irc:
        channels:
            - "irc.freenode.org#pyinstaller"
        use_notice: true
        # skip_join: true would require +n mode *not to be set on #pyinstaller
        skip_join: false
